### ISSUE TITLE
iOS/Android: Support printing capabilities

### ISSUE THREAD

**Issue by dethier1958** [tidev/titanium_mobile#13374]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

The Ti.Airprint module will not work in the XCode simulator on M1 Macs since it was not built for that processor. And since I would also need a module to convert html to a pdf to use ti.airprint in my app, even rebuilding that won't be enough.

And since Google no longer supports Google print, there is no good way to print from an Android app built with Titanium SDK. I am not aware of any modules that address printing on Android.

I would like to see printing for both iOS and Android added to Titanium SDK so no module is needed, or updated modules to handle printing on both platforms that will run in the simulator on an M1 Mac. Printing seems like a core function and should be included in a robust way.

Aside from this suggestion, I have been very much enjoying using VSCode and the Titanium extension on my M1 Mac. Builds go very fast. I really appreciate all the work that went into making the open-source transition work. The new API documentation is very good and very easy to use. Lots of other great documentation as well. Thanks!

### Solution

I would like to see printing included in Titanium SDK or new modules for printing for both iOS and Android that will run in the simulator on an M1 Mac as well.

### Alternatives

I have tried a few workarounds, include openURL to try to open Safari with an html file to print (this is what I do with my Android app, but this is a clumsy solution, and far from ideal). I also tried doing a webview and then doing evalJS to do window.print() but that didn't work. I'm not sure if that's something that could work with changes to Titanium SDK or if it's a limitation of iOS. But again, that's not an ideal solution. 

### Platforms

Android & iOS

**Comment by m1ga** [comment]
I think this is a good module functionality and shouldn't be included in the core as there is little demand for this and even if: it would take a long time to get this into the core. Asking at https://slack.tidev.io/ in #jobs for someone to develop a module would be a lot faster and also the module can be updated and maintained without the SDK release cycles. Perhaps someone evens has a working module. Otherwise I can look at the android implementation but don't have a printer I could connect to (I have a working [thermal printer module](https://github.com/m1ga/ti.thermalprinter))

**Comment by dethier1958** [comment]
I don't make enough on this app to be paying people to write modules for me. The ti.airprint module does work, but needs to be rebuilt to be able to run on an M1 Mac in the simulator. I suppose I can look into that. I have looked for modules online but have not been able to find anything. I will keep looking.

Is it possible to do something with webview so it will do window.print()? If that worked, I could handle printing that way.

**Comment by m1ga** [comment]
`You cannot use JavaScript in a HTML document to trigger printing.`
from https://developer.android.com/training/printing/html-docs.html

btw: I saw your issue in https://github.com/manumaticx/printmanager casue I had the same error and found it through google. I have a working version to print PDFs and images but it needs a patched SDK for now. 

Do you have any newer source of ti.airprint? I only found https://github.com/joewright/ti-airprint/

**Comment by dethier1958** [comment]
That limitation is for Android. I remember that from when Google dropped Google Print and I was trying to figure out how I could support printing in my Android app.

It's not clear whether iOS has this limitation. See: https://stackoverflow.com/questions/33319295/how-does-one-print-all-wkwebview-on-and-offscreen-content-osx-and-ios ... this is a very involved solution and probably not something you can do with Titanium.

For printing in my Android app, I settled on opening the content in a web browser using openURL, and then the user could print from there. Clumsy but it works. I tried doing this with iOS, but I could not get openURL to launch Safari with the html saved in my app's documents folder, either in the simulator or on my phone.

I will continue playing with this.

**Comment by dethier1958** [comment]
I believe that version of airprint is the current one, although it doesn't look like it's been touched for many years. Also, I think there is a bug: it has a flag to allow it to print html and a property to supply the html string, but you still need a url or it gives an error message. And printing html doesn't seem to work anyway. But I can toy around with that some more.

**Comment by m1ga** [comment]
ok, I thought you've said ti.airprint works and you just have to recompile it for M1. That's why I only looked at the Android part for now. That SO post looks like a lot of internal work :smile: Since it looks like its moving the print part out of the webview into the app.

Android:
Extended printmanager module:

https://user-images.githubusercontent.com/4334997/162626266-48a688c7-8abf-4555-b96d-ee15f2396b24.mp4

but it looks like you are just searching for an iOS solution so I'll don't do anything more with that one

**Comment by dethier1958** [comment]
I was playing with that Android module, but it never worked so I gave up on that. It would be nice if it did work, since that would be the Android solution, and much nicer than what I am having to do now.

Ti.Airprint does work when supplied with a pdf (but not in the simulator on an M1 Mac), so a rebuild should fix that. The bug I mentioned is probably very simple, just better testing for the url parameter and don't give an error if there is an html parameter. One or the other.

I would prefer to print using html since then I don't need the pdf creator module, which is also very old and not maintained.

**Comment by dethier1958** [comment]
> ok, I thought you've said ti.airprint works and you just have to recompile it for M1. That's why I only looked at the Android part for now. That SO post looks like a lot of internal work 😄 Since it looks like its moving the print part out of the webview into the app.
> 
> Android: Extended printmanager module:
> 
>  screencapture-2022-04-10_17.10.21.mp4 
> but it looks like you are just searching for an iOS solution so I'll don't do anything more with that one

Did you manage to get that Android print module working? If you did, could you share the code, because I was never able to get that far. I might use it if it works. Thanks!

**Comment by m1ga** [comment]
like I've mentioned above: only with a [patched SDK](https://github.com/m1ga/titanium_mobile/commit/5618e1a5fc476914672f460fd4e40cf70b5d78b4) because of this: https://stackoverflow.com/questions/37584094/getting-an-error-java-lang-illegalstateexception-can-print-only-from-an-activi/58888333#58888333
But I'm lookig for a solution for that with the current SDK.

**Comment by dethier1958** [comment]
Thanks!

**Comment by dethier1958** [comment]
Can anyone point me to information on how to build a module? I tried running build.py, but it can't find TiModule.h (I know where it is, but how to set things up so Python knows where it is). The manifest includes arm64. I think the target I need to add is AArch64 for the M1.

**Comment by m1ga** [comment]
I think the python way has been removed 5 years ago or so 😄 
https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_How-tos/Extending_Titanium_Mobile/iOS_Module_Development_Guide/iOS_Module_Quick_Start.html#build-and-package-the-module
It's just the normal build command `ti build -p ios --build-only` but I can't help you with the iOS part. Best way: join our slack.

**Comment by dethier1958** [comment]
Yes, this module is much older than that! I may create a new module and copy everything in. Then try to build. It will be an adventure!

**Comment by dethier1958** [comment]
After creating a new module and copying in the code, and doing a little editing to remove a deprecated property, I was able to build the module.

But I am still unable to build an app with the module using the Apple Silicon version of VS Code that will run in the simulator. I tried adding the aarch64 architecture, but doing so causes the build to fail. Is the Titanium SDK not able to do this yet?

The good news is that I downloaded the Intel VS Code and I can build and run my app in the simulator with that.

That was fun.

**Comment by m1ga** [comment]
Please join Slack :smile: we have some users there who updated modules for M1, they can help you there. Eg. check this thread if you are there: https://tidev.slack.com/archives/C03CVQX2A/p1646664393470589

**Comment by dethier1958** [comment]
How does one get an account on tidev.slack.com? I created an account on slack.com but that doesn't seem to be able to get me into tidev.slack.com ...

**Comment by m1ga** [comment]
it should be open for everyone to join :thinking: When you click on "sign up" doesn't it show you to login with your account?

**Comment by dethier1958** [comment]
There is no sign up option anywhere on the page.

**Comment by m1ga** [comment]
https://slack.tidev.io
![Screenshot_20220411_210833](https://user-images.githubusercontent.com/4334997/162812091-98d23fe1-44a8-4f2f-b917-cd2dfaa89dbb.png)

or try this invite: https://join.slack.com/t/tidev/shared_invite/zt-14qoze45t-Xx1NCSQ~akAEl70MVqjO_g

**Comment by dethier1958** [comment]
Thanks! Now I'm in ...

**Comment by dethier1958** [comment]
Spoke too soon about successfully building the module. When I try to use the module, none of my button events fire. Very odd! There were some warnings. This code is very old.

**Comment by dethier1958** [comment]
So I was able to build my modified ti.airprint module. It does load and it does work.

But if I use this module in my app, none of the event handlers for any button in my app work. The event handlers for clicking an item in a table work. The event handler for clicking a tabbed bar button works. But none of the button event handlers work. When I click on a button, the event handler is never fired.

If I replace the newly built module with the old module, everything works again.

Anyone have any ideas about what might be causing this? Seems very weird!

**Comment by m1ga** [comment]
Does it work when you just put an `alert(1)` into the button but keep the new module in your project? Sounds like something is infront of the button so you can't click it?
Or change the button to a view to check if you can click that. The module only has a few lines of code so shouldn't be that much to debug if it is the module and you have to go line by line. I don't have any ObjectivC knowledge so can't help you there.

**Comment by dethier1958** [comment]
I put a Ti.API.info in one of the event handlers and that never happened. The button does change appearance when I click on it, so I don't think anything is in front of it. I even tried moving one of the addEventListener calls to right when the view that had the button was made visible (long after the module was loaded).

I did call the module right when one view was loaded (without needing a button click) and it showed the airprint modal with the content I wanted to print, so the module seems to be working fine.

**Comment by dethier1958** [comment]
Since using the original ti.airprint module works and the new one does not, seems like that is the more likely cause. And it's only the buttons that don't work. All the other event handlers seem to work fine. Very odd.

**Comment by dethier1958** [comment]
I created a new module in VS Code, then replaced the code in the default module with the code from that old module. I did the build command from the terminal in VS Code after cd ios. The build runs, but there were some warnings, so I did make some changes to avoid those. I also made a minor change so it would not give an error when you wanted to print html but did not supply the url parameter.

I've programmed a lot in C, but never done anything with Objective-C or those frameworks, so I am trying not to change things I don't understand. A little guess and check there.

I very much appreciate the work on the Android print module and the Ti SDK 10.2.0 change. That will be a much better way to handle printing on Android.

**Comment by dethier1958** [comment]
I took my updated ti.airprint module and commented out almost everything that was not part of the new module that Ti SDK created. When I use this module, which does nothing, the button click handlers still do not work.

I'm going to try creating a new project with just a couple buttons (one with a click handler and one with a singletap handler) and a new module. I want to see what happens with the click handler in the most basic case.

**Comment by m1ga** [comment]
since you are on slack now have a look at this [thread](https://tidev.slack.com/archives/C03CVQX2A/p1647971357240729). 
One solution: deactivate `tap to click` in the options. But other people say that it randomly appeared to them too for a click on a button. Singletap works. 
But make sure to test it on a device, perhaps its only a simulator issue

**Comment by m1ga** [comment]
If you like you could upload your ti.airprint module to github so other people can benefit from it.
My module will be here once 10.2.0 will be available: https://github.com/m1ga/ti.print
I've pushed a quick bugfix to the SDK that needs to be merged. Then you can start using that and the Android module. So I think we can close this issue as the printing support is there now. The click/singletap issue should be a separate issue and not deep down in this issue

**Comment by dethier1958** [comment]
I still have some work to do on my updated ti.airprint ... I need to update the documentation to reflect a change I made, and I still need to build it so it will run on an M1 Mac in the simulator when built with the Apple Silicon version of VS Code. I've been build with the Intel version for now.

Once I get all that done, I will upload it for others to enjoy!

**Comment by dethier1958** [comment]
I was able to build ti.airprint for Apple Silicon (I just opened the XCode project and did all the suggested changes). I was able to build my app with the module using the Apple Silicon version of VS Code and run it in the simulator on my M1 Mac. I made some additional code changes to tidy things up. Tested on my iPhone.

The module is now available at [https://github.com/dethier1958/ti.airprint]

Thanks for all the help getting this done! I learned a lot. And it was fun.

**Comment by dethier1958** [comment]
Oh, and when I used the module built with Apple Silicon support, the problem where buttons would not do click events vanished. Clicking the buttons now works. Perhaps only a Rosetta issue?

**Comment by m1ga** [comment]
oh, that is an interesting information! Something to test. Thank you for the module! I'll promote it in slack so everyone knows about it :+1:

**Comment by m1ga** [comment]
I'll close this now since the Android part is now in 11.0.0.RC. If there are other issues (eg. the iOS part) feel free to open a new ticket.
